version: '3.8'

services:
  azure-rdp-bot:
    build: .
    container_name: azure-rdp-bot
    restart: unless-stopped
    environment:
      - AZURE_SPN_ID=${AZURE_SPN_ID}
      - AZURE_SPN_SECRET=${AZURE_SPN_SECRET}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_SUBSCRIPTION_ID=${AZURE_SUBSCRIPTION_ID}
    volumes:
      - ./data:/app/data
